In [ ]:
#pip install yfinance
#pip install pandas-datareader
#!pip install yahoofinancials
# Import necessary libraries
import yfinance as yf  # For fetching financial data
import datetime       # For working with date and time
import pandas as pd   # For data manipulation

In [ ]:
import numpy as np                    # For numerical operations
from scipy import stats                # For cheacking Outliers
import matplotlib.pyplot as plt        # For plotting
import seaborn as sns                  # For plotting
from statsmodels.tsa.seasonal import seasonal_decompose  # For seasonality analysis
import tensorflow as tf               # For machine learning using TensorFlow
from sklearn.model_selection import train_test_split  # For splitting the data
from sklearn.model_selection import GridSearchCV    # For hyperparameter tuning
from sklearn.metrics import mean_squared_error, r2_score  # For evaluating the model
from sklearn.preprocessing import StandardScaler       # For feature scaling
from sklearn.preprocessing import LabelEncoder          # For label encoding

E:\Anaconda\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [ ]:
from tensorflow import keras          # Keras, part of TensorFlow, for building neural networks
from sklearn.base import BaseEstimator, RegressorMixin  # For creating custom estimators
from tensorflow.keras.layers import Dense, SimpleRNN, LSTM  # For building neural network layers
# Define the stock symbol and date range

In [ ]:
symbol = "AAPL"                     # Stock symbol (in this case, Apple Inc.)
start_date = "2018-10-01"           # Start date for historical data
end_date = datetime.date.today().strftime("%Y-%m-%d")  # End date as today's date

# Fetch historical data using Yahoo Finance
data = yf.download(symbol, start=start_date, end=end_date)

# Create a DataFrame from the historical data
df = pd.DataFrame(data)

# Print the DataFrame containing the historical stock data
df

[*********************100%%**********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2018-10-01,56.987499,57.355000,56.587502,56.814999,54.413639,94403200
2018-10-02,56.812500,57.500000,56.657501,57.320000,54.897297,99152800
2018-10-03,57.512501,58.367500,57.445000,58.017502,55.565315,114619200
2018-10-04,57.695000,58.087502,56.682499,56.997501,54.588421,128168000
2018-10-05,56.990002,57.102501,55.145000,56.072498,53.702515,134322000
...,...,...,...,...,...,...
2023-11-01,171.000000,174.229996,170.119995,173.970001,173.970001,56934900
2023-11-02,175.520004,177.779999,175.460007,177.570007,177.570007,77334800
2023-11-03,174.240005,176.820007,173.350006,176.649994,176.649994,79763700
2023-11-06,176.380005,179.429993,176.210007,179.229996,179.229996,63841300
2023-11-07,179.179993,182.440002,178.970001,181.820007,181.820007,70464000